name: semopo
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.10
  - cryptography=35.0.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glew=2.1.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=4.8.2
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.2.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.2
  - jupyterlab=3.2.7
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.10
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.5
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.10
  - openssl=1.1.1n
  - packaging=21.3
  - pandocfilters=1.4.3
  - parso=0.8.3
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.1.2
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - ale-py==0.7.3
    - astunparse==1.6.3
    - atari-py==0.2.9
    - cachetools==4.2.4
    - cloudpickle==2.0.0
    - crafter==1.6.3
    - cycler==0.11.0
    - decorator==5.1.1
    - dill==0.3.4
    - dm-control==0.0.403778684
    - dm-env==1.5
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - fonttools==4.28.5
    - future==0.18.2
    - gast==0.4.0
    - glfw==2.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - gym==0.21.0
    - h5py==3.6.0
    - hickle==4.0.4
    - idna==3.3
    - imageio==2.13.5
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - joblib==1.1.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - labmaze==1.0.5
    - libclang==12.0.0
    - lxml==4.7.1
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy==1.22.0
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - opensimplex==0.4
    - opt-einsum==3.3.0
    - pandas==1.3.5
    - patchelf==0.14.3.0
    - pillow==9.0.0
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyopengl==3.1.5
    - pyparsing==3.0.6
    - pyyaml==6.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - sklearn==0.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-probability==0.15.0
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - tqdm==4.62.3
    - typing-extensions==4.0.1
    - werkzeug==2.0.2
    - wrapt==1.13.3
